/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author espir
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    FondoPanel fondo = new FondoPanel();

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        this.setContentPane(fondo);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnAgregarAtencion = new javax.swing.JMenuItem();
        mnAgregarDentista = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnEliminarAtencion = new javax.swing.JMenuItem();
        mnEliminarDentista = new javax.swing.JMenuItem();
        mnEliminarPaciente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnBuscarAtencion = new javax.swing.JMenuItem();
        mnBuscarDentista = new javax.swing.JMenuItem();
        mnBuscarPaciente = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Centro de Ortodoncia: Salazar & Galarce");
        setResizable(false);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("©All Rights Reserved Doppelganger 2020");

        jMenu1.setText("Ingresar");

        mnAgregarAtencion.setText("Agregar atención");
        mnAgregarAtencion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAgregarAtencionActionPerformed(evt);
            }
        });
        jMenu1.add(mnAgregarAtencion);

        mnAgregarDentista.setText("Agregar dentista");
        mnAgregarDentista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAgregarDentistaActionPerformed(evt);
            }
        });
        jMenu1.add(mnAgregarDentista);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Eliminar");

        mnEliminarAtencion.setText("Eliminar atención");
        mnEliminarAtencion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEliminarAtencionActionPerformed(evt);
            }
        });
        jMenu4.add(mnEliminarAtencion);

        mnEliminarDentista.setText("Eliminar dentista");
        mnEliminarDentista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEliminarDentistaActionPerformed(evt);
            }
        });
        jMenu4.add(mnEliminarDentista);

        mnEliminarPaciente.setText("Eliminar paciente");
        mnEliminarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEliminarPacienteActionPerformed(evt);
            }
        });
        jMenu4.add(mnEliminarPaciente);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Buscar");

        mnBuscarAtencion.setText("Buscar atención");
        mnBuscarAtencion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBuscarAtencionActionPerformed(evt);
            }
        });
        jMenu2.add(mnBuscarAtencion);

        mnBuscarDentista.setText("Buscar dentista");
        mnBuscarDentista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBuscarDentistaActionPerformed(evt);
            }
        });
        jMenu2.add(mnBuscarDentista);

        mnBuscarPaciente.setText("Buscar paciente");
        mnBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBuscarPacienteActionPerformed(evt);
            }
        });
        jMenu2.add(mnBuscarPaciente);

        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(255, 51, 51));
        jMenu3.setText("Salir");

        mnSalir.setText("Salir");
        mnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSalirActionPerformed(evt);
            }
        });
        jMenu3.add(mnSalir);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(542, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(377, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnEliminarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEliminarPacienteActionPerformed
        new VentanaEliminarPaciente().setVisible(true);
    }//GEN-LAST:event_mnEliminarPacienteActionPerformed

    private void mnAgregarDentistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAgregarDentistaActionPerformed
        new VentanaAgregarDentista().setVisible(true);
    }//GEN-LAST:event_mnAgregarDentistaActionPerformed

    private void mnAgregarAtencionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAgregarAtencionActionPerformed
        new VentanaAgregarAtencion().setVisible(true);
    }//GEN-LAST:event_mnAgregarAtencionActionPerformed

    private void mnEliminarDentistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEliminarDentistaActionPerformed
        new VentanaEliminarDentista().setVisible(true);
    }//GEN-LAST:event_mnEliminarDentistaActionPerformed

    private void mnBuscarAtencionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBuscarAtencionActionPerformed
        new VentanaBuscarAtencion().setVisible(true);
    }//GEN-LAST:event_mnBuscarAtencionActionPerformed

    private void mnEliminarAtencionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEliminarAtencionActionPerformed
        new VentanaEliminarAtencion().setVisible(true);
    }//GEN-LAST:event_mnEliminarAtencionActionPerformed

    private void mnBuscarDentistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBuscarDentistaActionPerformed
        new VentanaBuscarDentista().setVisible(true);
    }//GEN-LAST:event_mnBuscarDentistaActionPerformed

    private void mnBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBuscarPacienteActionPerformed
        new VentanaBuscarPaciente().setVisible(true);
    }//GEN-LAST:event_mnBuscarPacienteActionPerformed

    private void mnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnAgregarAtencion;
    private javax.swing.JMenuItem mnAgregarDentista;
    private javax.swing.JMenuItem mnBuscarAtencion;
    private javax.swing.JMenuItem mnBuscarDentista;
    private javax.swing.JMenuItem mnBuscarPaciente;
    private javax.swing.JMenuItem mnEliminarAtencion;
    private javax.swing.JMenuItem mnEliminarDentista;
    private javax.swing.JMenuItem mnEliminarPaciente;
    private javax.swing.JMenuItem mnSalir;
    // End of variables declaration//GEN-END:variables

    class FondoPanel extends JPanel {

        private Image imagen;
        
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/dentistawallpaper.jpg")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            
            super.paint(g);
        }
    }
    
}
