/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.AgendaAtenciones;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.Atencion;

/**
 *
 * @author espir
 */
public class VentanaBuscarAtencion extends javax.swing.JFrame {

    /**
     * Creates new form VentanaBuscarAtencion
     */
    public VentanaBuscarAtencion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSalida = new javax.swing.JTable();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar Atenciones");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Atención", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel1.setText("Fecha:");

        txtFecha.setToolTipText("Ej: 01/02/2020 o deje el campo en blanco para mostrar todas las atenciones");

        btnBuscar.setForeground(new java.awt.Color(102, 153, 0));
        btnBuscar.setText("Buscar");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tbSalida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Folio", "Paciente", "Fecha", "Hora", "Descripción", "Costo", "Dentista"
            }
        ));
        jScrollPane1.setViewportView(tbSalida);

        btnLimpiar.setForeground(new java.awt.Color(204, 153, 0));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String fecha = this.txtFecha.getText().trim();
        DefaultTableModel modeloLimpio = new DefaultTableModel();
        modeloLimpio.addColumn("Folio");
        modeloLimpio.addColumn("Paciente");
        modeloLimpio.addColumn("Fecha");
        modeloLimpio.addColumn("Hora");
        modeloLimpio.addColumn("Descripcion");
        modeloLimpio.addColumn("Costo");
        modeloLimpio.addColumn("Dentista");
        this.tbSalida.setModel(modeloLimpio); // Limpia la vista con una tabla vacia
        
        try {
            if (fecha.length() == 0) { //Si el campo txtFecha esta vacio muestra toda la BDD
                ArrayList<Atencion> lista = new AgendaAtenciones().buscarTodasAtenciones();
                if (lista.isEmpty()) {
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "No hay atenciones para mostrar, la base de datos esta vacia!!");
                } else {
                    DefaultTableModel modelo = new DefaultTableModel();
                    modelo.addColumn("Folio");
                    modelo.addColumn("Paciente");
                    modelo.addColumn("Fecha");
                    modelo.addColumn("Hora");
                    modelo.addColumn("Descripcion");
                    modelo.addColumn("Costo");
                    modelo.addColumn("Dentista");

                    for (Atencion ate : lista) {
                        Object[] fila = new Object[7];
                        fila[0] = ate.getFolio();
                        fila[1] = ate.getPaciente().getNombre();
                        fila[2] = ate.getFecha();
                        fila[3] = ate.getHora();
                        fila[4] = ate.getDescripcion();
                        fila[5] = ate.getCosto();
                        fila[6] = ate.getDentista().getNombre();
                        modelo.addRow(fila);
                    }
                    this.tbSalida.setModel(modelo);
                }

            } else {
                ArrayList<Atencion> lista = new AgendaAtenciones().buscarPorFecha(fecha);
                if (lista.isEmpty()) {
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "No se hallaron registros de atencion para la fecha: '" + fecha + "'.");
                } else {
                    DefaultTableModel modelo = new DefaultTableModel();
                    modelo.addColumn("Folio");
                    modelo.addColumn("Paciente");
                    modelo.addColumn("Fecha");
                    modelo.addColumn("Hora");
                    modelo.addColumn("Descripcion");
                    modelo.addColumn("Costo");
                    modelo.addColumn("Dentista");

                    for (Atencion ate : lista) {
                        Object[] fila = new Object[7];
                        fila[0] = ate.getFolio();
                        fila[1] = ate.getPaciente().getNombre();
                        fila[2] = ate.getFecha();
                        fila[3] = ate.getHora();
                        fila[4] = ate.getDescripcion();
                        fila[5] = ate.getCosto();
                        fila[6] = ate.getDentista().getNombre();
                        modelo.addRow(fila);
                    }
                    this.tbSalida.setModel(modelo);
                }
            }
        } catch (Exception e) {
            System.out.println("Error al buscar producto" + e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        this.txtFecha.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarAtencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarAtencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarAtencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarAtencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaBuscarAtencion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbSalida;
    private javax.swing.JTextField txtFecha;
    // End of variables declaration//GEN-END:variables
}
